### PR TITLE
Allow to save covariance matrix to file

### PR DESCRIPTION
**Pull request by mireianievas**

### CODE REVIEW

**Comment by mireianievas** [comment]
Needs to be tested, do not merge yet.

**Comment by davidsanchez** [comment]
Can I merge?

**Comment by mireianievas** [comment]
It seems to work. I just made a fine tune of the output format (affecting the header of the file). It should read something like:

```
### Covariance matrix. ###
#Parameters:
#1ES_0033+595::norm
#1ES_0033+595::alpha
#1ES_0033+595::beta

3.362790334742656873e-01,2.172058745700815481e-03,4.006870412145440569e-02
2.172058745700815481e-03,9.364105019069847381e-05,-3.017321533478121271e-04
4.006870412145440569e-02,-3.017321533478121271e-04,1.638526616501599989e-02
```

**Comment by davidsanchez** [comment]
thanks a lot @mireianievas

**Pull request merged**
