### PR TITLE
User tuneable TS threshold for weak source removal & cosmetic changes

### PR DESCRIPTION
**Pull request by mireianievas**
Config file now allows the user to specify a particular TS threshold for weak source removal. If sources have a TS value < target_TS (default = 1, previously fixed to = 1), they are removed from the model before doing a the final fit.

### CODE REVIEW

**Comment by mireianievas** [comment]
Added also a fix for the binsFromData option (sort FITS_rec table by TIME before computing the optimal time bins).

**Comment by davidsanchez** [comment]
Hi,

I will have a close look asap
thanks
david

**Comment by davidsanchez** [comment]
I'll merge everything once your done.

**Comment by mireianievas** [comment]
The tuneable TS threshold should be working (I've run enrico several times and it looks like it is working)
In the meantime, I've been working on 2 more options:

 - Recalculation of the spectral parameters at the decorrelation energy (now they are used in the written xml file and in the results file). This seems to be working.

 - SummedLikelihood: I've been working on several possibilities around this.
  - Front / Back events
  - PSF classes
  - EDISP classes
  - Binned for low energies (lots of events) / Unbinned for high energies (few events, it does make sense to compute the diffuse response here to extract as much info as possible from them).

So far, I've tried only the last case and it looks like it's finally working. I needed to do several changes in the code, where it tries to access logLike (to look for xml model parameter values for instance), it has to do it now component by component for that SummedLikelihood. In order to make it as straightforward as possible, I finally set the SummedLikelihood as the standard case and then, even if only 1 component is to be used (standard analysis).

**Comment by davidsanchez** [comment]
thanks for the work. I would not have time to deeply test it but I will have a look I'll merge it for now.
cheers
david

**Pull request merged**
