### PR TITLE
add analysis tags to new directories

### PR DESCRIPTION
**Pull request by zblz**
I have added the config['file']['tag'] to the newly generated paths (TSMap, Lightcurve, Spectrum) so that analysis with two different tags (but possibly sharing other files, such as the model) can be run in the same directory.

### CODE REVIEW

**Comment by davidsanchez** [comment]
Hi
one question. What happend for config['file']['tag'] = '' ? Is it backward compatible?
D

**Comment by zblz** [comment]
Leaving it empty will likely result in paths ending in _, which is probably not desirable. I could fix that with a few ifs.

Regarding backwards compatibility, this definitely breaks it, as the plot routines will not find the paths when they have been executed with an old version. I could do some checking in the plot routines: if the path with the tag is not found, search for a path without the tag. What do you think?

**Comment by davidsanchez** [comment]
I would prefere to not break backward compatibility for this.

**Comment by zblz** [comment]
Ok, fair enough.

**Pull request closed without merging**
